"""
BRD Content Validator.

After PDF text is extracted, sends it to an LLM with the original workflow
context and scores the BRD for accuracy, completeness, and structure.

Scoring dimensions:
  - completeness_score  (0-10): All required sections present?
  - accuracy_score      (0-10): Content matches the original prompt?
  - structure_score     (0-10): Proper BRD format and organisation?
  - requirement_score   (0-10): Functional requirements clear and testable?
  - overall_score       (0-10): Weighted average
  - verdict             pass | partial | fail
  - missing_sections    [str]
  - issues              [str]
  - highlights          [str]
  - section_scores      {section: 0-10}
"""

import json
import logging
import os
import re
from typing import Optional

from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()
logger = logging.getLogger(__name__)

_BRD_REQUIRED_SECTIONS = [
    "executive summary",
    "business objectives",
    "scope",
    "functional requirements",
    "non-functional requirements",
    "stakeholders",
    "assumptions",
    "constraints",
    "acceptance criteria",
]

# Required sections by document type
_SECTIONS_BY_TYPE = {
    "PRD": ["overview", "problem statement", "goals", "user stories", "functional requirements",
            "non-functional requirements", "acceptance criteria", "out of scope"],
    "BRD": ["executive summary", "business objectives", "scope", "functional requirements",
            "non-functional requirements", "stakeholders", "assumptions", "constraints",
            "acceptance criteria"],
    "Architecture Doc": ["overview", "architecture", "components", "data flow", "technology stack",
                         "security", "scalability", "deployment"],
    "Runbook": ["purpose", "prerequisites", "steps", "troubleshooting", "rollback"],
    "Literature Review": ["introduction", "methodology", "themes", "findings", "gaps", "conclusion"],
}

_BRD_SYSTEM_PROMPT = """You are a senior technical writer, business analyst, and QA engineer evaluating a document generated by SAI (Adya AI's Super AI Agent Platform).

The document may be a PRD, BRD, Architecture Doc, Runbook, Literature Review, or other technical document.

You will receive:
1. The original user request (workflow prompt)
2. The persona context (who requested it)
3. The document type (auto-detected)
4. The full document text extracted from the downloaded PDF

Evaluate the BRD on FIVE dimensions:

1. COMPLETENESS (completeness_score 0-10)
   - Are all standard BRD sections present? (Executive Summary, Business Objectives, Scope, Functional Requirements, Non-Functional Requirements, Stakeholders, Assumptions, Constraints, Acceptance Criteria)
   - Score 0 if fewer than 3 sections, 5 if half present, 10 if all present and non-empty

2. ACCURACY (accuracy_score 0-10)
   - Does the BRD content accurately reflect the original user request?
   - Are all key features/requirements from the prompt captured?
   - Is the business context (industry, persona) correctly reflected?
   - Score 0 if content is completely unrelated, 10 if everything from prompt is accurately represented

3. STRUCTURE (structure_score 0-10)
   - Is the BRD well-organised with clear section headings?
   - Is the language professional and unambiguous?
   - Are requirements numbered and traceable?
   - Score 0 if unstructured, 10 if follows standard BRD format perfectly

4. REQUIREMENT QUALITY (requirement_score 0-10)
   - Are functional requirements specific, measurable, and testable?
   - Are non-functional requirements defined (performance, security, scalability)?
   - Are acceptance criteria present and unambiguous?
   - Flag any vague/generic requirements like "the system shall be user-friendly"

5. OVERALL (overall_score 0-10)
   - Weighted average: completeness×0.25 + accuracy×0.30 + structure×0.20 + requirement×0.25

verdict rules:
  - overall_score >= 7 → "pass"
  - overall_score >= 5 → "partial"
  - overall_score < 5  → "fail"

Return ONLY valid JSON with this exact structure:
{
  "completeness_score": <int 0-10>,
  "accuracy_score": <int 0-10>,
  "structure_score": <int 0-10>,
  "requirement_score": <int 0-10>,
  "overall_score": <int 0-10>,
  "verdict": "pass" | "partial" | "fail",
  "missing_sections": ["section name", ...],
  "issues": ["specific issue 1", ...],
  "highlights": ["what was done well 1", ...],
  "section_scores": {"Executive Summary": <int>, ...},
  "rationale": "<2-3 sentence summary>"
}"""


class BRDValidator:
    """
    Validates a BRD PDF against the original workflow prompt using an LLM.
    """

    def __init__(self):
        api_key = os.getenv("OPENAI_API_KEY", "")
        base_url = os.getenv("OPENAI_BASE_URL", "")
        self._model = os.getenv("JUDGE_MODEL", "grok-3-beta")

        kwargs: dict = {"api_key": api_key}
        if base_url:
            kwargs["base_url"] = base_url
        self._client = OpenAI(**kwargs)

    def validate(
        self,
        brd_text: str,
        workflow: dict,
        persona: dict,
        pdf_extraction: dict,
        doc_type: str = "Document",
    ) -> dict:
        """
        Validate a SAI-generated document (PRD, BRD, Architecture Doc, etc.).

        Args:
            brd_text:       Full text extracted from PDF
            workflow:       Workflow dict
            persona:        Persona dict
            pdf_extraction: Output from pdf_extractor.extract_text()
            doc_type:       "PRD" | "BRD" | "Architecture Doc" | "Runbook" | etc.

        Returns: validation result dict with scores, verdict, issues, highlights.
        """
        result = _empty_result()
        result["doc_type"]    = doc_type
        result["pdf_path"]    = pdf_extraction.get("path", "")
        result["pdf_pages"]   = pdf_extraction.get("pages", 0)
        result["pdf_chars"]   = pdf_extraction.get("char_count", 0)
        result["brd_text_preview"] = brd_text[:500] if brd_text else ""

        if not brd_text or len(brd_text.strip()) < 50:
            result["verdict"] = "fail"
            result["issues"].append(f"{doc_type} text is empty or too short to evaluate")
            result["overall_score"] = 0
            logger.warning("[DocValidator] %s text too short (%d chars)", doc_type, len(brd_text or ""))
            return result

        # Rule-based pre-check using type-specific required sections
        required_sections = _SECTIONS_BY_TYPE.get(doc_type, _BRD_REQUIRED_SECTIONS)
        text_lower = brd_text.lower()
        missing = [s for s in required_sections if s not in text_lower]
        present = [s for s in required_sections if s in text_lower]
        result["missing_sections"] = missing
        result["sections_found"]   = present

        # Build LLM prompt with doc type context
        user_content = _build_user_prompt(brd_text, workflow, persona, doc_type)

        try:
            response = self._client.chat.completions.create(
                model=self._model,
                messages=[
                    {"role": "system", "content": _BRD_SYSTEM_PROMPT},
                    {"role": "user",   "content": user_content},
                ],
                temperature=0.1,
                max_tokens=1500,
            )
            raw = response.choices[0].message.content or ""
            tokens = getattr(response.usage, "total_tokens", 0)
            result["tokens_used"] = tokens
            logger.info("[BRDValidator] LLM responded (%d tokens)", tokens)

            parsed = _parse_json(raw)
            if parsed:
                result.update(parsed)
                # Merge rule-based missing sections with LLM findings
                llm_missing = parsed.get("missing_sections", [])
                all_missing = list(set(missing + llm_missing))
                result["missing_sections"] = all_missing
                logger.info(
                    "[BRDValidator] verdict=%s overall=%s completeness=%s accuracy=%s",
                    result.get("verdict"),
                    result.get("overall_score"),
                    result.get("completeness_score"),
                    result.get("accuracy_score"),
                )
            else:
                logger.warning("[BRDValidator] Could not parse LLM JSON, using rule-based fallback")
                result = _rule_based_fallback(result, brd_text, workflow)

        except Exception as e:
            logger.error("[BRDValidator] LLM call failed: %s", e)
            result["error"] = str(e)
            result = _rule_based_fallback(result, brd_text, workflow)

        return result


# ── Helpers ───────────────────────────────────────────────────────────────────

def _empty_result() -> dict:
    return {
        "doc_type":           "Document",
        "completeness_score": 0,
        "accuracy_score":     0,
        "structure_score":    0,
        "requirement_score":  0,
        "overall_score":      0,
        "verdict":            "fail",
        "missing_sections":   [],
        "sections_found":     [],
        "issues":             [],
        "highlights":         [],
        "section_scores":     {},
        "rationale":          "",
        "tokens_used":        0,
        "pdf_path":           "",
        "pdf_pages":          0,
        "pdf_chars":          0,
        "brd_text_preview":   "",
        "error":              None,
    }


def _build_user_prompt(brd_text: str, workflow: dict, persona: dict,
                       doc_type: str = "Document") -> str:
    required = _SECTIONS_BY_TYPE.get(doc_type, _BRD_REQUIRED_SECTIONS)
    prompt_parts = [
        f"=== DOCUMENT TYPE: {doc_type} ===",
        f"Required sections for a {doc_type}: {', '.join(required)}",
        "",
        "=== ORIGINAL USER REQUEST ===",
        workflow.get("initial_prompt", "(not provided)"),
        "",
        "=== PERSONA CONTEXT ===",
        f"Name: {persona.get('name', '?')}",
        f"Role: {persona.get('role', '?')}",
        f"Goals: {', '.join(persona.get('goals', [])[:3])}",
        "",
        "=== WORKFLOW EVALUATION CRITERIA ===",
        f"Process: {(workflow.get('evaluation_criteria') or {}).get('process', '(none)')}",
        f"Output:  {(workflow.get('evaluation_criteria') or {}).get('output',  '(none)')}",
        "",
        f"=== {doc_type.upper()} TEXT (from downloaded PDF — {len(brd_text)} chars) ===",
        brd_text[:8000],   # cap at 8000 to stay within context window
    ]
    if len(brd_text) > 8000:
        prompt_parts.append(f"\n[... {len(brd_text) - 8000} additional chars truncated ...]")

    return "\n".join(prompt_parts)


def _parse_json(raw: str) -> Optional[dict]:
    """Extract and parse JSON from LLM response."""
    # Strip markdown code fences
    raw = re.sub(r"```(?:json)?\s*", "", raw).strip("` \n")
    try:
        return json.loads(raw)
    except Exception:
        # Try to find the first {...} block
        m = re.search(r"\{[\s\S]+\}", raw)
        if m:
            try:
                return json.loads(m.group())
            except Exception:
                pass
    return None


def _rule_based_fallback(result: dict, brd_text: str, workflow: dict) -> dict:
    """
    Simple rule-based scoring when the LLM is unavailable.
    Scores based on keyword presence and text length.
    """
    text_lower = brd_text.lower()
    prompt_words = set(
        re.findall(r"\b\w{4,}\b",
                   workflow.get("initial_prompt", "").lower())
    )

    # Completeness: count required sections found
    present = sum(1 for s in _BRD_REQUIRED_SECTIONS if s in text_lower)
    completeness = round(present / len(_BRD_REQUIRED_SECTIONS) * 10)

    # Accuracy: what fraction of key prompt words appear in the BRD
    if prompt_words:
        matched = sum(1 for w in prompt_words if w in text_lower)
        accuracy = min(10, round(matched / len(prompt_words) * 15))
    else:
        accuracy = 5

    # Structure: heading markers present
    headings = len(re.findall(r"(?m)^#{1,3}\s+\S|^\d+\.\s+[A-Z]", brd_text))
    structure = min(10, headings)

    # Requirement quality: numbered requirements
    reqs = len(re.findall(r"(?m)^(?:FR|NFR|REQ|R)[-\s]?\d+", brd_text, re.IGNORECASE))
    requirement = min(10, reqs)

    overall = round(
        completeness * 0.25 + accuracy * 0.30 + structure * 0.20 + requirement * 0.25
    )
    verdict = "pass" if overall >= 7 else ("partial" if overall >= 5 else "fail")

    result.update({
        "completeness_score": completeness,
        "accuracy_score":     accuracy,
        "structure_score":    structure,
        "requirement_score":  requirement,
        "overall_score":      overall,
        "verdict":            verdict,
        "rationale":          f"Rule-based fallback: {present}/{len(_BRD_REQUIRED_SECTIONS)} sections found, {accuracy}/10 accuracy.",
    })
    return result
